#!/bin/sh
#
# chkconfig: 235 20 07
# description: Activates/deactivates all vlans and routes to make GriVon-VMs to reach this host.

RETVAL=0

start() {
    if [ ! -f /var/lock/subsys/grivon-server-vlan ]; then
	echo -n $"Starting GriVon Server VLAN: "
	echo
	/etc/vmware-grivon/grivon-server-vlan.pl --start
	echo
	touch /var/lock/subsys/grivon-server-vlan
    fi
    return $RETVAL
}

stop() {
    echo -n $"Stopping GriVon Server VLAN: "
    echo
    /etc/vmware-grivon/grivon-server-vlan.pl --stop
    rm -f /var/lock/subsys/grivon-server-vlan
    echo
    return $RETVAL
}

restart() {
    stop
    start
}

status() {
    /etc/vmware-grivon/grivon-server-vlan.pl --status
}

case "$1" in
start)
	start
	;;
stop)
	stop
	;;
restart)
	restart
	;;
condrestart)
	if [ -f /var/lock/subsys/grivon-server-vlan ]; then
	    restart
	fi
	;;
status)
	status
	;;
*)
	echo $"Usage: $0 {start|stop|status|restart|condrestart}"
	exit 1
esac

exit $RETVAL
